### ISSUE TITLE
NoLinkToConceptScheme is to restrictive

### ISSUE THREAD

**Issue by acka47** [skohub-io/shapes#1]
With https://github.com/skohub-io/skohub-vocabs/pull/230 we made it possible to only add one of the inverse relations '`hasTopConcept` or `topConceptOf` in SkoHub Vocabs. The Shape does not reflect this change yet and thus a build won't start in skohub-docker-vocabs:

https://github.com/skohub-io/shapes/blob/61d50c3046d157042e2581b8a48988dc64578044/skos.shacl.ttl#L156-L175

**Comment by sroertgen** [comment]
I just noticed that the SKOS-Reference allows orphaned concept schemes: https://www.w3.org/TR/skos-reference/#L2497

So this rule is too restrictive anyway. I think about combining it with `:OrphanConcepts` and just give a warning. 

https://github.com/skohub-io/shapes/blob/61d50c3046d157042e2581b8a48988dc64578044/skos.shacl.ttl#L178-L201

**Comment by acka47** [comment]
> I just noticed that the SKOS-Reference allows orphaned concept schemes: https://www.w3.org/TR/skos-reference/#L2497

You mean orphaned _concepts_.  However, this must not mean that we must allow it in SKoHub Vocabs.

>  I think about combining it with :OrphanConcepts and just give a warning.

+1 This is a very good solution.
