### ISSUE TITLE
Better handling of warnings in GitHub Action

### ISSUE THREAD

**Issue by acka47** [skohub-io/shapes#18]
For background, see discussion in reference implementation at https://github.com/dini-ag-kim/hochschulfaechersystematik/pull/40

**Comment by dr0i** [comment]
Now I see that the handling is already the intented one - we don't want to just ignore WARNINGS (which I had in mind). So I think the scripts are working perfectly.
You should satisfy the tests so that all WARNINGS disappear.
Closing.
