### ISSUE TITLE
Add examples from SKOS Reference as test cases

### ISSUE THREAD

**Issue by nichtich** [skohub-io/shapes#7]
All examples of [SKOS Reference](https://www.w3.org/TR/skos-reference/) should be included as test cases. For instance `skos-reference-example-12-invalid.ttl`

~~~turtle
<Love> skos:prefLabel "love"@en ; skos:prefLabel "adoration"@en .
~~~

**Comment by sroertgen** [comment]
see https://github.com/skohub-io/shapes/issues/6#issuecomment-1721023757 :)

**Comment by sroertgen** [comment]
@nichtich I assign you here, since I'm not able to do so in the PR
